[project]
name = "tikitarai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=5.0.0",
    "cryptography>=50.0.0",
    "pillow>=12.3.0",
    "streamlit>=1.60.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
